//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        [Key]
        public int CustomerId { get; set; }
        public string Email { get; set; }
        public decimal Balance { get; set; }
        public Nullable<int> ProductsId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
